ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
storage:
    type: $DB_TYPE
    url: $DB_URL
    user: $DB_USER
    password: $DB_PASSWORD